name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Run tests
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./yarn.lock
      - run: docker-compose -f docker-compose.test.yml --env-file .env.test run url-shortener-api-test
